Repository apache/horaedb, pull requests merged in 2022-07, with the labels that each got.

#73 feat: new flush policy - purge flush
  analytic_engine/src/instance/flush_compaction.rs
  analytic_engine/src/table/metrics.rs
  analytic_engine/src/table/version.rs
Labels: enhancement

#101 refactor: remove `Store` type param in `Instance`
  Cargo.lock
  analytic_engine/src/compaction/scheduler.rs
  analytic_engine/src/engine.rs
  analytic_engine/src/instance/alter.rs
  analytic_engine/src/instance/close.rs
  analytic_engine/src/instance/create.rs
  analytic_engine/src/instance/drop.rs
  analytic_engine/src/instance/engine.rs
  analytic_engine/src/instance/flush_compaction.rs
  analytic_engine/src/instance/mod.rs
  analytic_engine/src/instance/open.rs
  analytic_engine/src/instance/read.rs
  analytic_engine/src/instance/write.rs
  analytic_engine/src/instance/write_worker.rs
  analytic_engine/src/row_iter/chain.rs
  analytic_engine/src/row_iter/merge.rs
  analytic_engine/src/row_iter/record_batch_stream.rs
  analytic_engine/src/setup.rs
  analytic_engine/src/sst/factory.rs
  analytic_engine/src/sst/file.rs
  analytic_engine/src/sst/parquet/builder.rs
  analytic_engine/src/sst/parquet/reader.rs
  analytic_engine/src/storage_options.rs
  analytic_engine/src/table/mod.rs
  benchmarks/src/merge_memtable_bench.rs
  benchmarks/src/merge_sst_bench.rs
  benchmarks/src/parquet_bench.rs
  benchmarks/src/scan_memtable_bench.rs
  benchmarks/src/sst_bench.rs
  benchmarks/src/sst_tools.rs
  benchmarks/src/util.rs
  components/object_store/Cargo.toml
  components/object_store/src/cache.rs
  components/object_store/src/lib.rs
  docs/example.toml
Labels: enhancement

#79 docs: propose prometheus read extension
  docs/rfcs/20220702-prometheus-read-extension.md
Labels: documentation

#99 feat: Support more expressions in predicate pushdown
  analytic_engine/src/instance/flush_compaction.rs
  analytic_engine/src/instance/read.rs
  analytic_engine/src/row_iter/record_batch_stream.rs
  analytic_engine/src/sst/parquet/builder.rs
  analytic_engine/src/table/mod.rs
  analytic_engine/src/tests/table.rs
  benchmarks/src/config.rs
  benchmarks/src/merge_memtable_bench.rs
  benchmarks/src/merge_sst_bench.rs
  benchmarks/src/parquet_bench.rs
  benchmarks/src/sst_bench.rs
  benchmarks/src/sst_tools.rs
  benchmarks/src/util.rs
  table_engine/src/predicate/mod.rs
  table_engine/src/provider.rs
Labels: enhancement

#116 fix: table name with quote
  sql/src/ast.rs
  sql/src/parser.rs
  sql/src/planner.rs
Labels: A-SQL

#134 docs: user guide about static routing
  docs/user-guide/src/deploy/README.md
  docs/user-guide/src/deploy/static_routing.md
Labels: documentation

#142 Minor Grammar and Concision Changes in README.md
  README.md
Labels: documentation

#100 refactor: enhance cluster module based on meta_client_v2
  Cargo.lock
  Cargo.toml
  analytic_engine/src/tests/util.rs
  ceresdbproto_deps/Cargo.toml
  ceresdbproto_deps/src/lib.rs
  cluster/src/cluster_impl.rs
  cluster/src/config.rs
  cluster/src/lib.rs
  cluster/src/table_manager.rs
  cluster/src/util.rs
  meta_client/Cargo.toml
  meta_client/src/lib.rs
  meta_client_v2/Cargo.toml
  meta_client_v2/src/lib.rs
  meta_client_v2/src/meta_impl.rs
  meta_client_v2/src/types.rs
  server/src/config.rs
  server/src/grpc/mod.rs
  src/bin/ceresdb-server.rs
  src/setup.rs
  table_engine/src/engine.rs
Labels: A-cluster

#152 build(image): :hammer: replace entrypoint with bash, drop supervisor
  Dockerfile
  docker/entrypoint.py
  docker/entrypoint.sh
  docker/supervisor/conf.d/ceresdb.conf
  docker/supervisor/supervisord.conf
Labels: enhancement

#160 docs: add integration test section to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#159 refactor: make write method object safe in WalManager
  analytic_engine/src/instance/write.rs
  analytic_engine/src/meta/details.rs
  analytic_engine/src/meta/meta_update.rs
  analytic_engine/src/payload.rs
  components/bytes/src/lib.rs
  wal/src/kv_encoder.rs
  wal/src/log_batch.rs
  wal/src/manager.rs
  wal/src/rocks_impl/encoding.rs
  wal/src/rocks_impl/manager.rs
  wal/src/table_kv_impl/encoding.rs
  wal/src/table_kv_impl/namespace.rs
  wal/src/table_kv_impl/region.rs
  wal/src/table_kv_impl/wal.rs
  wal/src/tests/read_write.rs
  wal/src/tests/util.rs
Labels: enhancement, A-analytic-engine
