Repository apache/horaedb, pull requests merged in 2024-10, with the labels that each got.

#1576 fix: remove redundancy length field in wal record
  .asf.yaml
  .github/workflows/ci.yml
  .github/workflows/tsbs.yml
  Cargo.lock
  Cargo.toml
  docs/example-cluster-0.toml
  docs/example-cluster-1.toml
  docs/example-standalone-static-routing.toml
  docs/minimal.toml
  integration_tests/Makefile
  integration_tests/cases/env/cluster/ddl/partition_table.result
  integration_tests/cases/env/cluster/ddl/partition_table.sql
  integration_tests/cases/env/local/ddl/query-plan.result
  integration_tests/config/horaedb-cluster-0.toml
  integration_tests/config/horaedb-cluster-1.toml
  integration_tests/config/shard-based-recovery.toml
  src/horaedb/Cargo.toml
  src/wal/Cargo.toml
  src/wal/src/local_storage_impl/record_encoding.rs
  src/wal/src/local_storage_impl/segment.rs
Labels: bug

#1578 chore: bump version 2.1.0
  Cargo.lock
  Cargo.toml
  src/wal/src/local_storage_impl/config.rs
  src/wal/src/local_storage_impl/segment.rs
  src/wal/src/local_storage_impl/wal_manager.rs
Labels: chore

#1579 chore: fix license header
  .github/workflows/ci.yml
  Makefile
  horaemeta/go.mod
  integration_tests/sdk/go/go.mod
  licenserc.toml
Labels: chore

#1581 chore: support type `test`, `build` and `style` in pr title
  .github/workflows/check-pr-title.yml
Labels: chore

#1582 chore: update community
  .github/workflows/links.yml
  CONTRIBUTING.md
  README-CN.md
  README.md
  docs/rfcs/20220702-prometheus-read-extension.md
  horaemeta/CONTRIBUTING.md
Labels: chore

#1563 feat: support horaedb submit compaction task to remote
  Cargo.lock
  Cargo.toml
  src/analytic_engine/Cargo.toml
  src/analytic_engine/src/compaction/mod.rs
  src/analytic_engine/src/compaction/runner/local_runner.rs
  src/analytic_engine/src/compaction/runner/mod.rs
  src/analytic_engine/src/compaction/runner/node_picker.rs
  src/analytic_engine/src/compaction/runner/remote_client.rs
  src/analytic_engine/src/compaction/runner/remote_runner.rs
  src/analytic_engine/src/instance/engine.rs
  src/analytic_engine/src/instance/flush_compaction.rs
  src/analytic_engine/src/instance/open.rs
  src/analytic_engine/src/lib.rs
  src/analytic_engine/src/setup.rs
  src/analytic_engine/src/sst/factory.rs
  src/analytic_engine/src/sst/file.rs
  src/analytic_engine/src/sst/writer.rs
  src/analytic_engine/src/table_options.rs
  src/analytic_engine/src/tests/util.rs
  src/benchmarks/src/util.rs
  src/cluster/src/cluster_impl.rs
  src/cluster/src/config.rs
  src/cluster/src/lib.rs
  src/common_types/src/cluster.rs
  src/common_types/src/lib.rs
  src/horaedb/Cargo.toml
  src/horaedb/src/config.rs
  src/horaedb/src/setup.rs
  src/meta_client/src/lib.rs
  src/meta_client/src/meta_impl.rs
  src/meta_client/src/types.rs
  src/router/src/cluster_based.rs
  src/server/src/grpc/compaction_service/error.rs
  src/server/src/grpc/compaction_service/mod.rs
  src/server/src/grpc/mod.rs
  src/server/src/server.rs
  src/table_engine/src/predicate.rs
  src/table_engine/src/table.rs
Labels: feature
