Repository apache/horaedb, pull requests merged in 2024-08, with the labels that each got.

#1546 refactor: manifest error code
  src/analytic_engine/src/instance/engine.rs
  src/analytic_engine/src/manifest/details.rs
  src/analytic_engine/src/manifest/error.rs
  src/analytic_engine/src/manifest/meta_edit.rs
  src/analytic_engine/src/manifest/meta_snapshot.rs
  src/analytic_engine/src/manifest/mod.rs
  src/analytic_engine/src/memtable/key.rs
  src/analytic_engine/src/table_meta_set_impl.rs
Labels: refactor

#1550 fix: sequence overflow when dropping a table using a message queue as WAL
  src/wal/src/message_queue_impl/wal.rs
Labels: bug

#1541 chore: upgrade object store version
  Cargo.lock
  src/analytic_engine/src/setup.rs
  src/analytic_engine/src/sst/meta_data/cache.rs
  src/analytic_engine/src/sst/parquet/writer.rs
  src/components/object_store/Cargo.toml
  src/components/object_store/src/config.rs
  src/components/object_store/src/disk_cache.rs
  src/components/object_store/src/lib.rs
  src/components/object_store/src/mem_cache.rs
  src/components/object_store/src/metrics.rs
  src/components/object_store/src/multi_part.rs
  src/components/object_store/src/multipart.rs
  src/components/object_store/src/obkv/meta.rs
  src/components/object_store/src/obkv/mod.rs
  src/components/object_store/src/obkv/util.rs
  src/components/object_store/src/prefix.rs
  src/components/object_store/src/test_util.rs
  src/tools/src/bin/sst-metadata.rs
Labels: chore

#1558 feat: add metric engine rfc
  docs/rfcs/20240827-metric-engine.md
  docs/rfcs/resources/root-table.png
Labels: feature

#1561 chore: update link
  horaemeta/README.md
Labels: chore
