Repository apache/horaedb, pull requests merged in 2024-12, with the labels that each got.

#1603 feat: support pick ssts in compact
  horaedb/Cargo.lock
  horaedb/Cargo.toml
  horaedb/metric_engine/Cargo.toml
  horaedb/metric_engine/src/compaction/mod.rs
  horaedb/metric_engine/src/compaction/picker.rs
  horaedb/metric_engine/src/compaction/scheduler.rs
  horaedb/metric_engine/src/sst.rs
  horaedb/metric_engine/src/types.rs
Labels: feature

#1604 feat: another format for manifest
  horaedb/Cargo.lock
  horaedb/Cargo.toml
  horaedb/metric_engine/Cargo.toml
  horaedb/metric_engine/src/manifest.rs
Labels: feature

#1605 feat: support merge operator
  horaedb/metric_engine/Cargo.toml
  horaedb/metric_engine/src/lib.rs
  horaedb/metric_engine/src/operator.rs
  horaedb/metric_engine/src/read.rs
  horaedb/metric_engine/src/storage.rs
  horaedb/metric_engine/src/test_util.rs
  horaedb/metric_engine/src/types.rs
Labels: feature

#1609 feat: add compaction runner
  Cargo.lock
  Cargo.toml
  Makefile
  src/metric_engine/Cargo.toml
  src/metric_engine/src/compaction/mod.rs
  src/metric_engine/src/compaction/runner.rs
  src/metric_engine/src/compaction/scheduler.rs
  src/metric_engine/src/manifest.rs
  src/metric_engine/src/read.rs
  src/metric_engine/src/storage.rs
  src/metric_engine/src/types.rs
Labels: feature

#1611 refactor: move encoding struct into independent file
  src/metric_engine/src/compaction/executor.rs
  src/metric_engine/src/manifest/encoding.rs
  src/metric_engine/src/manifest/mod.rs
Labels: refactor

#1612 refactor: use `Read` trait to convert Bytes to Snapshot
  .github/workflows/ci.yml
  src/metric_engine/src/manifest/encoding.rs
Labels: refactor

#1614 feat: add demo server for benchmark
  Cargo.lock
  src/metric_engine/src/compaction/scheduler.rs
  src/metric_engine/src/storage.rs
  src/server/Cargo.toml
  src/server/src/main.rs
Labels: feature

#1616 fix: manifest delta num may overflow
  Cargo.lock
  docs/example.toml
  src/benchmarks/src/encoding_bench.rs
  src/metric_engine/Cargo.toml
  src/metric_engine/src/compaction/executor.rs
  src/metric_engine/src/compaction/mod.rs
  src/metric_engine/src/compaction/picker.rs
  src/metric_engine/src/compaction/scheduler.rs
  src/metric_engine/src/config.rs
  src/metric_engine/src/lib.rs
  src/metric_engine/src/manifest/encoding.rs
  src/metric_engine/src/manifest/mod.rs
  src/metric_engine/src/read.rs
  src/metric_engine/src/sst.rs
  src/metric_engine/src/storage.rs
  src/metric_engine/src/types.rs
  src/server/Cargo.toml
  src/server/src/config.rs
  src/server/src/main.rs
Labels: bug, chore

#1617 fix: scan with predicate
  Cargo.lock
  src/metric_engine/src/compaction/scheduler.rs
  src/metric_engine/src/read.rs
  src/metric_engine/src/storage.rs
Labels: bug

#1618 feat: skip add sequence column when compact
  Cargo.toml
  src/benchmarks/Cargo.toml
  src/common/Cargo.toml
  src/metric_engine/Cargo.toml
  src/metric_engine/src/compaction/executor.rs
  src/metric_engine/src/read.rs
  src/metric_engine/src/storage.rs
  src/pb_types/Cargo.toml
  src/server/Cargo.toml
Labels: feature

#1619 refactor: add more `macro` in config
  src/metric_engine/src/compaction/scheduler.rs
  src/metric_engine/src/config.rs
Labels: refactor

#1620 feat: add reserved column
  Cargo.lock
  src/metric_engine/Cargo.toml
  src/metric_engine/src/compaction/executor.rs
  src/metric_engine/src/operator.rs
  src/metric_engine/src/read.rs
  src/metric_engine/src/storage.rs
  src/metric_engine/src/test_util.rs
  src/metric_engine/src/types.rs
Labels: feature
