Repository apache/horaedb, pull requests merged in 2024-11, with the labels that each got.

#1518 chore: add publish-github-release action
  .github/release.yml
  .github/workflows/publish-github-release.yml
Labels: chore

#1584 feat: add a cli tool to read wal meta information
  Cargo.lock
  Cargo.toml
  src/tools/Cargo.toml
  src/tools/src/bin/wal-reader.rs
  src/wal/src/local_storage_impl/mod.rs
  src/wal/src/local_storage_impl/segment.rs
Labels: feature

#1585 feat: sort record batch of write request
  .github/workflows/metric-engine-ci.yml
  horaedb/Cargo.lock
  horaedb/Cargo.toml
  horaedb/Makefile
  horaedb/metric_engine/src/storage.rs
Labels: feature

#1586 feat: init scan implementation for time merge storage
  horaedb/metric_engine/src/lib.rs
  horaedb/metric_engine/src/manifest.rs
  horaedb/metric_engine/src/read.rs
  horaedb/metric_engine/src/sst.rs
  horaedb/metric_engine/src/storage.rs
  horaedb/metric_engine/src/types.rs
  horaedb/pb_types/protos/sst.proto
Labels: feature

#1587 chore: fix LICENSE and NOTICE
  LICENSE
  NOTICE
Labels: chore

#1588 refactor: make writing properties independently
  horaedb/metric_engine/src/storage.rs
  horaedb/metric_engine/src/types.rs
Labels: refactor

#1590 fix: skip build latest docker tag for RC version.
  .github/workflows/publish-image.yml
Labels: bug

#1593 fix: avoid splicing bucket multiple times in oss url
  src/components/object_store/src/aliyun.rs
Labels: bug

#1596 feat: support persist manifest efficientlly
  horaedb/Cargo.lock
  horaedb/metric_engine/Cargo.toml
  horaedb/metric_engine/src/manifest.rs
  horaedb/metric_engine/src/storage.rs
Labels: feature

#1598 chore: bump to v2.2.0-dev
  Cargo.lock
  Cargo.toml
  integration_tests/cases/env/cluster/config.toml
  integration_tests/cases/env/compaction_offload/config.toml
  integration_tests/cases/env/local/config.toml
  src/analytic_engine/src/lib.rs
  src/components/object_store/src/disk_cache.rs
  src/wal/src/config.rs
Labels: chore

#1594 feat: partition table query optimize
  integration_tests/cases/env/cluster/ddl/partition_table.result
  integration_tests/cases/env/cluster/ddl/partition_table.sql
  src/df_engine_extensions/src/dist_sql_query/physical_plan.rs
  src/df_engine_extensions/src/dist_sql_query/resolver.rs
  src/df_engine_extensions/src/dist_sql_query/test_util.rs
  src/partition_table_engine/src/lib.rs
  src/partition_table_engine/src/partition.rs
  src/partition_table_engine/src/scan_builder.rs
  src/table_engine/src/engine.rs
  src/table_engine/src/partition/rule/df_adapter/extractor.rs
  src/table_engine/src/partition/rule/df_adapter/mod.rs
  src/table_engine/src/partition/rule/key.rs
  src/table_engine/src/partition/rule/mod.rs
  src/table_engine/src/partition/rule/random.rs
  src/table_engine/src/predicate.rs
Labels: feature
