Repository apache/horaedb, pull requests merged in 2024-05, with the labels that each got.

#1526 refactor: allow disable wal in standalone mode
  src/horaedb/src/setup.rs
Labels: refactor

#1528 chore: add dingtalk
  README-CN.md
  README.md
Labels: chore

#1529 fix: docker image use apache namespace
  .github/workflows/publish-image.yml
  .github/workflows/test-build-image.yml
  README-CN.md
  README.md
  horaemeta/Dockerfile
Labels: bug

#1531 feat: impl basic auth
  Cargo.lock
  src/proxy/Cargo.toml
  src/proxy/src/auth/mod.rs
  src/proxy/src/auth/with_file.rs
  src/proxy/src/context.rs
  src/proxy/src/forward.rs
  src/proxy/src/grpc/prom_query.rs
  src/proxy/src/grpc/sql_query.rs
  src/proxy/src/http/prom.rs
  src/proxy/src/http/sql.rs
  src/proxy/src/influxdb/mod.rs
  src/proxy/src/lib.rs
  src/proxy/src/opentsdb/mod.rs
  src/proxy/src/read.rs
  src/proxy/src/write.rs
  src/server/src/config.rs
  src/server/src/grpc/mod.rs
  src/server/src/grpc/storage_service/mod.rs
  src/server/src/http.rs
  src/server/src/server.rs
Labels: feature

#1532 chore: add incubating notice
  .asf.yaml
  .github/workflows/meta-ci.yml
  README-CN.md
  README.md
  horaemeta/README.md
  horaemeta/licenserc.toml
Labels: chore

#1535 docs: Update README.md
  README.md
Labels: docs
