Repository apache/horaedb, pull requests merged in 2024-09, with the labels that each got.

#1556 feat: Implementing cross-segment read/write for WAL based on local disk
  src/wal/src/local_storage_impl/config.rs
  src/wal/src/local_storage_impl/record_encoding.rs
  src/wal/src/local_storage_impl/segment.rs
  src/wal/src/local_storage_impl/wal_manager.rs
Labels: feature

#1565 chore: fix doc links
  CONTRIBUTING.md
  README-CN.md
  README.md
Labels: chore

#1533 fix: disable layered memtable in overwrite mode
  Cargo.lock
  Cargo.toml
  integration_tests/cases/common/dml/case_sensitive.result
  integration_tests/cases/common/show/show_create_table.result
  integration_tests/cases/env/cluster/ddl/alter_table.result
  integration_tests/cases/env/cluster/ddl/create_tables.result
  integration_tests/cases/env/cluster/ddl/partition_table.result
  integration_tests/cases/env/local/ddl/alter_table.result
  integration_tests/cases/env/local/ddl/alter_table.sql
  integration_tests/cases/env/local/ddl/create_tables.result
  integration_tests/cases/env/local/ddl/create_tables.sql
  integration_tests/cases/env/local/ddl/sampling-primary-key.result
  src/analytic_engine/src/instance/alter.rs
  src/analytic_engine/src/instance/create.rs
  src/analytic_engine/src/instance/engine.rs
  src/analytic_engine/src/lib.rs
  src/analytic_engine/src/memtable/mod.rs
  src/analytic_engine/src/table/data.rs
  src/analytic_engine/src/table_options.rs
  src/common_types/src/lib.rs
  src/system_catalog/src/sys_catalog_table.rs
  src/table_engine/src/engine.rs
Labels: bug

#1554 feat: init metric engine structure
  .github/workflows/metric-engine-ci.yml
  horaedb/Cargo.lock
  horaedb/Cargo.toml
  horaedb/Makefile
  horaedb/metric_engine/Cargo.toml
  horaedb/metric_engine/src/error.rs
  horaedb/metric_engine/src/lib.rs
  horaedb/metric_engine/src/manifest.rs
  horaedb/metric_engine/src/sst.rs
  horaedb/metric_engine/src/storage.rs
  horaedb/metric_engine/src/types.rs
  horaedb/server/Cargo.toml
  horaedb/server/src/main.rs
Labels: feature

#1566 feat: Implement delete operation for WAL based on local storage
  Cargo.lock
  src/analytic_engine/src/instance/write.rs
  src/wal/Cargo.toml
  src/wal/src/local_storage_impl/config.rs
  src/wal/src/local_storage_impl/segment.rs
  src/wal/src/local_storage_impl/wal_manager.rs
  src/wal/tests/read_write.rs
Labels: feature

#1568 fix: support to compat the old layered memtable options
  src/analytic_engine/src/instance/open.rs
  src/analytic_engine/src/lib.rs
  src/analytic_engine/src/manifest/details.rs
  src/analytic_engine/src/table/data.rs
  src/analytic_engine/src/table_meta_set_impl.rs
Labels: bug, chore

#1569 chore: record replay cost in log
  src/analytic_engine/src/instance/wal_replayer.rs
  src/analytic_engine/src/lib.rs
  src/server/src/http.rs
Labels: chore

#1570 fix: logs might be missed during RegionBased replay in the WAL based on local disk
  src/analytic_engine/src/instance/wal_replayer.rs
Labels: bug
